# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
utils::globalVariables(c("_StatComp22090_gibbsC"))

#' @name gibbs
#' @title gibbs sample by Rcpp
#' @description Generate the gibbs sample by Rcpp,using the method of gibbs sampling.
#' @param N the sample size
#' @return a Numeric Matrix,sp stands for random sample of multivariate distribution.
#' @examples
#' \dontrun{
#' res <- gibbsC(5000)
#' }
#' @export
gibbsC <- function(N) {
    .Call(`_StatComp22090_gibbsC`, N)
}

